# Generated by Django 3.1.7 on 2021-04-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('AR', 'Статья'), ('NS', 'Новость')], default='AR', max_length=255),
        ),
    ]
