# Generated by Django 3.2 on 2021-06-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Группы'),
        ),
    ]
